; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; C:\Users\lukar\.platformio\penv\Scripts\platformio.exe run -t upload -e remote
; C:\Users\lukar\.platformio\penv\Scripts\platformio.exe run -t upload -e buggy

; C:\Users\lukar\.platformio\penv\Scripts\platformio.exe device monitor -p COM3
; C:\Users\lukar\.platformio\penv\Scripts\platformio.exe device monitor -p COM4

[env:remote]
platform = atmelavr
board = nanoatmega328new
framework = arduino
lib_deps = 
	arduino-libraries/LiquidCrystal@^1.0.7
	nrf24/RF24@^1.6.1
build_src_filter =
    +<remote_main.cpp>
    -<buggy_main.cpp>

[env:buggy]
platform = atmelavr
board = nanoatmega328new
framework = arduino
lib_deps = 
	arduino-libraries/LiquidCrystal@^1.0.7
	nrf24/RF24@^1.6.1
build_src_filter =
    +<buggy_main.cpp>
    -<remote_main.cpp>